// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Form__AutomationController from "./form/automation_controller"
application.register("form--automation", Form__AutomationController)

import Form__ConfigurationController from "./form/configuration_controller"
application.register("form--configuration", Form__ConfigurationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)
